name: Deployment AWS/ECR
on:
  # push:
  # branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build React app
    runs-on: ubuntu-latest
    env:
      REACT_APP_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
      REACT_APP_MAPTILER_TOKEN: ${{ secrets.MAPTILER_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: action/cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: CI=false npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: build

  deploy-to-aws-ecr:
    name: Build Docker Image and deploy to AWS ECR
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: build

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG